theme: jekyll-theme-minimal
name: Ameek Bindra
baseurl: "/about-me"
url: "https://ameeki.github.io"
permalink: pretty

search_enabled: true
search_tokenizer_separator: /[\s/]+/

heading_anchors: true

aux_links:
  "My page on GitHub":
    - "//github.com/Ameeki/Ameeki.github.io"
    
footer_content: "Copyright &copy; 2020 Ameek Bindra."
logo: "/assets/images/just-the-docs.png"

color_scheme: nil

plugins:
  - jekyll-seo-tag
  
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
